build:
	sbt assembly
	
run-non-blocking:
	java -jar .\target\scala-3.1.0\DiningPhilosophersProblem-assembly-0.1.0-SNAPSHOT.jar
	
run-blocking:
	java -jar .\target\scala-3.1.0\DiningPhilosophersProblem-assembly-0.1.0-SNAPSHOT.jar 1
