build:
	sbt assembly
	
run-non-blocking:
	java -cp .\target\scala-3.1.0\DiningPhilosophersProblem-assembly-0.1.0-SNAPSHOT.jar DiningPhilosophersProblem
	
run-blocking:
	java -cp .\target\scala-3.1.0\DiningPhilosophersProblem-assembly-0.1.0-SNAPSHOT.jar DiningPhilosophersProblemBlocking